-- AlterTable
ALTER TABLE "Kitten" ALTER COLUMN "birthdate" SET DATA TYPE TIMESTAMPTZ(0);

-- AlterTable
ALTER TABLE "KittenDataPoint" ALTER COLUMN "time" SET DATA TYPE TIMESTAMPTZ(0);

-- AlterTable
ALTER TABLE "KittenPost" ALTER COLUMN "created_at" SET DATA TYPE TIMESTAMPTZ(0),
ALTER COLUMN "updated_at" SET DATA TYPE TIMESTAMPTZ(0);

-- AlterTable
ALTER TABLE "Post" ALTER COLUMN "created_at" SET DATA TYPE TIMESTAMPTZ(0),
ALTER COLUMN "updated_at" SET DATA TYPE TIMESTAMPTZ(0);
